// Generated by CoffeeScript 1.3.3
var adjustUI;

adjustUI = function(numBots) {
  if (numBots === 1) {
    $('#botsh').hide();
    $('#bots').hide();
    return datatable.fnSetColumnVis(5, false);
  } else {
    return $('#info').hide();
  }
};

$(document).ready(function() {
  $('#searchbox').focus();
  $('#searchbox').keyup(function() {
    datatable.fnFilter(this.value, 2, true, true);
    return datatable.fnAdjustColumnSizing();
  });
  $('#packlist').css('height', window.innerHeight);
  $(window).resize(function() {
    return $('#packlist').css('height', window.innerHeight);
  });
  $('#packlisttable tbody').click(function(event) {
    var botnick, num, str;
    console.log(event);
    num = event.target.parentNode.childNodes[0].childNodes[0].nodeValue;
    botnick = event.target.parentNode.childNodes[5].childNodes[0].nodeValue;
    str = '/msg ' + botnick + ' xdcc send ' + num;
    return window.prompt('Copy and paste this into your IRC client', str);
  });
  return $('#lists .head').click(function() {
    $(this).next().slideToggle(50);
    return false;
  });
});
