// Generated by CoffeeScript 1.3.3
var adjustUI, closeBotInfo, openBotInfo;

adjustUI = function(numBots) {
  if (numBots === 1) {
    $('#botsh').hide();
    $('#bots').hide();
    datatable.fnSetColumnVis(5, false);
    datatable.fnAdjustColumnSizing();
    return openBotInfo(packlistArr[0]);
  } else {
    return $('#info').hide();
  }
};

openBotInfo = function(id) {
  var cat, i, _i, _len, _ref;
  infotable.fnClearTable();
  _ref = infoHash[id][0];
  for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
    cat = _ref[i];
    infotable.fnAddData([cat, infoHash[id][1][i]]);
  }
  $('#infoh').addClass('toggleable');
  return $('#info').slideDown(50);
};

closeBotInfo = function() {
  $('#infoh').removeClass('toggleable');
  return $('#info').slideUp(50);
};

$(document).ready(function() {
  $('#searchbox').focus();
  $('#searchbox').keyup(function() {
    datatable.fnFilter(this.value, 2, true, true);
    return datatable.fnAdjustColumnSizing();
  });
  $('#packlist').css('height', window.innerHeight);
  $(window).resize(function() {
    return $('#packlist').css('height', window.innerHeight);
  });
  $('#packlisttable tbody').click(function(event) {
    var botnick, num, str;
    if (event.target.parentNode.childNodes[5] === void 0) {
      botnick = Object.keys(revhash)[0];
      console.log(botnick);
    } else {
      botnick = event.target.parentNode.childNodes[5].childNodes[0].nodeValue;
    }
    num = event.target.parentNode.childNodes[0].childNodes[0].nodeValue;
    str = '/msg ' + botnick + ' xdcc send ' + num;
    return window.prompt('Copy and paste this into your IRC client', str);
  });
  $('#bottable tbody').click(function(event) {
    var nick;
    nick = event.target.parentNode.childNodes[0].childNodes[0].nodeValue;
    datatable.fnFilter(nick, 5);
    datatable.fnAdjustColumnSizing();
    return openBotInfo(revhash[nick]);
  });
  $('#allbots').click(function(event) {
    datatable.fnFilter('', 5);
    closeBotInfo();
    return false;
  });
  return $('body').on('click', 'h3.toggleable', function() {
    $(this).next().slideToggle(50);
    return false;
  });
});
