// Generated by CoffeeScript 1.3.3

$(document).ready(function() {
  $('#searchbox').focus();
  $('#packlist').css('height', window.innerHeight);
  $(window).resize(function() {
    return $('#packlist').css('height', window.innerHeight);
  });
  return $('#packlisttable tbody').click(function(event) {
    var botnick, num, str;
    console.log(event);
    num = event.target.parentNode.childNodes[0].childNodes[0].nodeValue;
    botnick = event.target.parentNode.childNodes[5].childNodes[0].nodeValue;
    str = '/msg ' + botnick + ' xdcc send ' + num;
    return window.prompt('Copy and paste this into your IRC client', str);
  });
});
